// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the
//     code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------

#ifndef TECHNIQUES
// begin SAMPLERS
sampler uImage0 : register(s0);
// end SAMPLERS

// begin UNIFORMS
float4 uSource;
float uTime;
float uPixel;
// end UNIFORMS
#endif // TECHNIQUES

// begin PASSES
#ifdef FX
#ifdef TECHNIQUES
technique Technique1
{
    pass FlowerShader
    {
        PixelShader = compile ps_3_0 main();
    }
}
#endif // TECHNIQUES
#endif // FX
// end PASSES
