// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the
//     code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------

// begin SAMPLERS
sampler uImage0 : register(s0);
// end SAMPLERS

// begin UNIFORMS
float uTime;
float4 uSource;
float uHoverIntensity;
float uPixel;
float uColorResolution;
float uGrayness;
float3 uInColor;
float uSpeed;
// end UNIFORMS
