// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the
//     code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------

#ifndef TECHNIQUES
// begin SAMPLERS
// end SAMPLERS

// begin UNIFORMS
matrix uTransformMatrix;
// end UNIFORMS
#endif // TECHNIQUES

// begin PASSES
#ifdef FX
#ifdef TECHNIQUES
technique Technique1
{
    pass StripShader
    {
        PixelShader = compile ps_3_0 pixel();
        VertexShader = compile vs_3_0 vertex();
    }
}
#endif // TECHNIQUES
#endif // FX
// end PASSES
