// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the
//     code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------

#ifndef TECHNIQUES
// begin SAMPLERS
// end SAMPLERS

// begin UNIFORMS
// end UNIFORMS
#endif // TECHNIQUES

// begin PASSES
#ifdef FX
#ifdef TECHNIQUES
technique Technique1
{
    pass MagicMissile
    {
        PixelShader = compile ps_3_0 magic_missile();
    }
    pass FinalFractalVertex
    {
        PixelShader = compile ps_3_0 final_fractal_vertex();
    }
}
#endif // TECHNIQUES
#endif // FX
// end PASSES
